version: '2'
services:
  harbor-adapter-clair:
    image: bitnami/harbor-adapter-clair:1
    ports:
      - 8080:8080
    volumes:
      - harbor-adapter-clair_data:/bitnami
volumes:
  harbor-adapter-clair_data:
    driver: local
